export interface StackPreset {
  name: string;
  framework: string;
  orm: string;
  auth: string;
  ui_library: string;
  conventions: string[];
  patterns: Record<string, string>;
  file_structure: string;
  dependencies: string[];
  anti_patterns: string[];
}

export const STACK_PRESETS: Record<string, StackPreset> = {
  'nextjs-supabase-shadcn': {
    name: 'nextjs-supabase-shadcn',
    framework: 'Next.js 15 (App Router)',
    orm: 'Supabase (Postgres + PostgREST)',
    auth: 'Supabase Auth (email/password + social)',
    ui_library: 'shadcn/ui + Tailwind CSS 4',
    conventions: [
      'TypeScript strict mode, no `any`',
      'Server Components by default, \'use client\' only when needed',
      'File-based routing with app/ directory',
      'Named exports for components',
      'Colocate components with their routes',
      'Use Supabase RLS for all data access policies',
      'Environment variables prefixed with NEXT_PUBLIC_ for client-side',
    ],
    patterns: {
      auth: 'Supabase createClient() with server/client separation',
      data_fetching: 'Server Components for reads, Server Actions for writes',
      file_upload: 'Supabase Storage with signed URLs',
      realtime: 'Supabase Realtime subscriptions',
      forms: 'react-hook-form + zod validation + shadcn Form component',
    },
    file_structure: 'app/(auth)/, app/(dashboard)/, components/ui/, lib/supabase/, types/',
    dependencies: ['next@15', 'react@19', '@supabase/supabase-js', '@supabase/ssr', 'tailwindcss', 'shadcn/ui', 'zod', 'react-hook-form'],
    anti_patterns: [
      'Never use getServerSideProps (use Server Components)',
      'Never access Supabase client-side without RLS',
      'Never store secrets in NEXT_PUBLIC_ variables',
      'Never use useEffect for data fetching (use Server Components)',
      'Never skip loading/error states in async components',
      'Avoid client components for static content',
      'Never disable TypeScript strict mode',
    ],
  },
  't3-stack': {
    name: 't3-stack',
    framework: 'Next.js 15 (App Router)',
    orm: 'Prisma ORM',
    auth: 'NextAuth.js (Auth.js v5)',
    ui_library: 'Tailwind CSS',
    conventions: [
      'TypeScript strict, no any',
      'tRPC for all API calls (end-to-end type safety)',
      'Prisma schema as single source of truth for types',
      'Server-first data fetching via tRPC callers',
      'Zod for runtime validation',
    ],
    patterns: {
      auth: 'NextAuth with Prisma adapter',
      data_fetching: 'tRPC procedures (query/mutation)',
      api: 'tRPC router with input validation via Zod',
      middleware: 'NextAuth middleware for protected routes',
    },
    file_structure: 'src/app/, src/server/api/routers/, src/server/auth.ts, src/server/db.ts, src/trpc/',
    dependencies: ['next@15', '@trpc/server', '@trpc/client', '@trpc/react-query', 'prisma', '@prisma/client', 'next-auth', 'zod', 'tailwindcss'],
    anti_patterns: [
      'Never bypass tRPC for API calls (use fetch only for external APIs)',
      'Never write raw SQL (use Prisma)',
      'Never skip input validation on tRPC procedures',
      'Never expose server-only code to client bundles',
      'Never use untyped env variables (use t3-env)',
    ],
  },
  'react-native-expo': {
    name: 'react-native-expo',
    framework: 'Expo (React Native)',
    orm: 'Firebase Firestore',
    auth: 'Firebase Auth',
    ui_library: 'React Native Paper',
    conventions: [
      'TypeScript strict',
      'Functional components with hooks',
      'Expo Router for navigation',
      'AsyncStorage for local persistence',
    ],
    patterns: {
      auth: 'Firebase Auth with expo-auth-session',
      data_fetching: 'Firestore onSnapshot for realtime',
      navigation: 'Expo Router (file-based)',
      state: 'Zustand for global state',
    },
    file_structure: 'app/ (Expo Router), components/, hooks/, lib/, constants/',
    dependencies: ['expo', 'react-native', 'firebase', 'expo-router', 'zustand', 'react-native-paper'],
    anti_patterns: [
      'Never use inline styles for reused components',
      'Never block the JS thread with heavy computation',
      'Never store sensitive data in AsyncStorage (use SecureStore)',
      'Never skip platform-specific testing (iOS + Android)',
      'Never use web-only APIs without Platform checks',
    ],
  },
  'python-fastapi': {
    name: 'python-fastapi',
    framework: 'FastAPI',
    orm: 'SQLAlchemy 2.0 + Alembic',
    auth: 'JWT (python-jose) + OAuth2',
    ui_library: 'none (API-only)',
    conventions: [
      'Type hints on all functions',
      'Pydantic models for request/response validation',
      'Dependency injection via FastAPI Depends()',
      'Async handlers where possible',
      'tests/ mirror src/ structure',
    ],
    patterns: {
      auth: 'OAuth2 password bearer + JWT tokens',
      data_fetching: 'SQLAlchemy async sessions',
      migrations: 'Alembic auto-generate',
      validation: 'Pydantic BaseModel',
    },
    file_structure: 'app/main.py, app/models/, app/schemas/, app/routers/, app/services/, alembic/, tests/',
    dependencies: ['fastapi', 'uvicorn', 'sqlalchemy[asyncio]', 'alembic', 'pydantic', 'python-jose', 'passlib[bcrypt]', 'httpx', 'pytest'],
    anti_patterns: [
      'Never use global database sessions',
      'Never skip Pydantic validation for inputs',
      'Never hardcode secrets (use pydantic-settings)',
      'Never use sync I/O in async handlers',
      'Never skip database migrations',
    ],
  },
  'vue-nuxt-pinia': {
    name: 'vue-nuxt-pinia',
    framework: 'Nuxt 3',
    orm: 'Supabase',
    auth: 'Supabase Auth (via @nuxtjs/supabase)',
    ui_library: 'Nuxt UI',
    conventions: [
      'TypeScript strict',
      'Composition API (setup script)',
      'Auto-imports enabled',
      'Pinia stores for global state',
      'Server routes for API',
    ],
    patterns: {
      auth: '@nuxtjs/supabase module',
      data_fetching: 'useFetch / useAsyncData composables',
      state: 'Pinia stores with setup syntax',
      forms: 'VeeValidate + Zod',
    },
    file_structure: 'pages/, components/, composables/, stores/, server/api/, layouts/',
    dependencies: ['nuxt', '@pinia/nuxt', '@nuxtjs/supabase', '@nuxt/ui', 'zod'],
    anti_patterns: [
      'Never use Options API (use Composition API)',
      'Never mutate props directly',
      'Never skip SSR considerations for client-only code',
      'Never use $fetch in components (use useFetch)',
      'Never store auth tokens manually (use @nuxtjs/supabase)',
    ],
  },
  'sveltekit-drizzle': {
    name: 'sveltekit-drizzle',
    framework: 'SvelteKit',
    orm: 'Drizzle ORM',
    auth: 'Lucia Auth v3',
    ui_library: 'Tailwind CSS + Bits UI',
    conventions: [
      'TypeScript strict',
      'Runes for state ($state, $derived)',
      'Form actions for mutations',
      'Load functions for data',
      'Drizzle schema as type source',
    ],
    patterns: {
      auth: 'Lucia with Drizzle adapter',
      data_fetching: 'SvelteKit load functions',
      forms: 'SvelteKit form actions + superforms',
      state: 'Svelte runes ($state)',
    },
    file_structure: 'src/routes/, src/lib/server/db/, src/lib/server/auth.ts, src/lib/components/',
    dependencies: ['@sveltejs/kit', 'svelte', 'drizzle-orm', 'lucia', 'tailwindcss'],
    anti_patterns: [
      'Never access database from client-side code',
      'Never use stores when runes suffice',
      'Never skip form validation on server side',
      'Never use +page.js when +page.server.ts is needed',
      'Never expose server-only imports to client',
    ],
  },
  'flutter-firebase': {
    name: 'flutter-firebase',
    framework: 'Flutter 3',
    orm: 'Cloud Firestore',
    auth: 'Firebase Auth',
    ui_library: 'Material 3',
    conventions: [
      'Riverpod for state management',
      'Freezed for immutable models',
      'GoRouter for navigation',
      'Repository pattern for data access',
    ],
    patterns: {
      auth: 'Firebase Auth with StreamProvider',
      data_fetching: 'Firestore streams via Riverpod',
      state: 'Riverpod providers (AsyncNotifier)',
      navigation: 'GoRouter with guards',
    },
    file_structure: 'lib/features/[feature]/presentation|domain|data/, lib/core/, lib/routing/, lib/main.dart',
    dependencies: ['flutter', 'firebase_core', 'firebase_auth', 'cloud_firestore', 'flutter_riverpod', 'freezed', 'go_router'],
    anti_patterns: [
      'Never use setState for complex state (use Riverpod)',
      'Never put business logic in widgets',
      'Never skip null safety',
      'Never hardcode strings (use l10n)',
      'Never block UI thread with heavy computation',
    ],
  },
  'django-htmx': {
    name: 'django-htmx',
    framework: 'Django 5',
    orm: 'Django ORM',
    auth: 'Django Auth + allauth',
    ui_library: 'Tailwind CSS + HTMX',
    conventions: [
      'Class-based views for CRUD, function views for custom logic',
      'Django templates with HTMX for interactivity',
      'django-environ for settings',
      'pytest-django for testing',
    ],
    patterns: {
      auth: 'django-allauth (social + email)',
      data_fetching: 'Django ORM querysets',
      forms: 'Django ModelForm + crispy-forms',
      interactivity: 'HTMX (hx-get, hx-post, hx-swap)',
    },
    file_structure: 'project/settings/base|dev|prod.py, apps/[app_name]/models|views|urls|templates|forms|tests/',
    dependencies: ['django', 'django-htmx', 'django-allauth', 'django-environ', 'whitenoise', 'gunicorn', 'tailwindcss'],
    anti_patterns: [
      'Never use raw SQL without Django ORM parameterization',
      'Never disable CSRF protection',
      'Never put secrets in settings.py (use environ)',
      'Never use function views for standard CRUD',
      'Never skip database migrations before deployment',
    ],
  },
};

// Additional stacks (Go, Rust, Rails, Laravel, Spring Boot, .NET)
export const ADDITIONAL_STACK_PRESETS: Record<string, StackPreset> = {
  'go-fiber': {
    name: 'go-fiber',
    framework: 'Go + Fiber v2',
    orm: 'GORM',
    auth: 'JWT (golang-jwt)',
    ui_library: 'none (API-only)',
    conventions: [
      'Standard Go project layout (cmd/, internal/, pkg/)',
      'Error handling with explicit returns, no panic in handlers',
      'Context propagation for cancellation and timeouts',
      'Table-driven tests',
      'Dependency injection via constructor functions',
    ],
    patterns: {
      auth: 'JWT middleware with refresh token rotation',
      data_fetching: 'Repository pattern with GORM',
      validation: 'go-playground/validator struct tags',
      middleware: 'Fiber middleware chain',
    },
    file_structure: 'cmd/api/main.go, internal/handlers/, internal/models/, internal/repository/, internal/middleware/, pkg/',
    dependencies: ['github.com/gofiber/fiber/v2', 'gorm.io/gorm', 'gorm.io/driver/postgres', 'github.com/golang-jwt/jwt/v5'],
    anti_patterns: [
      'Never use global state — pass dependencies explicitly',
      'Never ignore errors — always handle or propagate',
      'Never use init() for complex logic',
      'Never expose internal packages via pkg/',
      'Never use panic for control flow',
    ],
  },
  'rust-axum': {
    name: 'rust-axum',
    framework: 'Rust + Axum',
    orm: 'SQLx (compile-time checked queries)',
    auth: 'axum-extra + JWT',
    ui_library: 'none (API-only)',
    conventions: [
      'Type-driven development — make invalid states unrepresentable',
      'Error types with thiserror + anyhow for application errors',
      'Async with tokio runtime',
      'Tower middleware for cross-cutting concerns',
      'Integration tests in tests/ directory',
    ],
    patterns: {
      auth: 'Extractors for authenticated routes',
      data_fetching: 'SQLx with compile-time query checking',
      state: 'Arc<AppState> shared via Extension',
      errors: 'Custom error type implementing IntoResponse',
    },
    file_structure: 'src/main.rs, src/routes/, src/models/, src/db/, src/errors.rs, src/middleware/, tests/',
    dependencies: ['axum', 'tokio', 'sqlx', 'serde', 'tower', 'tracing'],
    anti_patterns: [
      'Never use unwrap() in production code — use ? operator',
      'Never clone unnecessarily — use references and lifetimes',
      'Never block the async runtime with sync I/O',
      'Never use String when &str suffices',
      'Never skip error handling with _ = ',
    ],
  },
  'rails-hotwire': {
    name: 'rails-hotwire',
    framework: 'Ruby on Rails 7',
    orm: 'ActiveRecord',
    auth: 'Devise + OmniAuth',
    ui_library: 'Hotwire (Turbo + Stimulus) + Tailwind',
    conventions: [
      'Convention over configuration',
      'RESTful routes and resources',
      'Fat models, skinny controllers',
      'Service objects for complex business logic',
      'RSpec for testing with FactoryBot',
    ],
    patterns: {
      auth: 'Devise with confirmable + lockable',
      data_fetching: 'ActiveRecord scopes and includes (N+1 prevention)',
      realtime: 'Turbo Streams over ActionCable',
      background: 'Sidekiq for async jobs',
    },
    file_structure: 'app/controllers/, app/models/, app/views/, app/services/, app/jobs/, spec/',
    dependencies: ['rails', 'devise', 'sidekiq', 'turbo-rails', 'stimulus-rails', 'tailwindcss-rails'],
    anti_patterns: [
      'Never put business logic in controllers',
      'Never skip database indexes on foreign keys',
      'Never use N+1 queries (use includes/preload)',
      'Never skip validations in models',
      'Never commit credentials (use Rails credentials)',
    ],
  },
  'laravel-inertia': {
    name: 'laravel-inertia',
    framework: 'Laravel 11',
    orm: 'Eloquent ORM',
    auth: 'Laravel Breeze / Sanctum',
    ui_library: 'Inertia.js + Vue 3 + Tailwind',
    conventions: [
      'PSR-12 coding standard',
      'Form Request classes for validation',
      'Resource controllers for CRUD',
      'Eloquent API Resources for responses',
      'Feature tests with PHPUnit / Pest',
    ],
    patterns: {
      auth: 'Sanctum for SPA + API token auth',
      data_fetching: 'Inertia shared props + lazy loading',
      validation: 'Form Request classes with authorize()',
      background: 'Laravel Queues with Redis/SQS',
    },
    file_structure: 'app/Http/Controllers/, app/Models/, app/Services/, resources/js/Pages/, database/migrations/, tests/',
    dependencies: ['laravel/framework', 'inertiajs/inertia-laravel', 'laravel/sanctum', 'vue', 'tailwindcss'],
    anti_patterns: [
      'Never put logic in routes file — use controllers',
      'Never skip Form Request validation',
      'Never use raw queries without bindings (SQL injection)',
      'Never commit .env file',
      'Never skip database migrations (no manual DB changes)',
    ],
  },
  'spring-boot': {
    name: 'spring-boot',
    framework: 'Spring Boot 3 (Java 21 / Kotlin)',
    orm: 'Spring Data JPA + Hibernate',
    auth: 'Spring Security + OAuth2',
    ui_library: 'none (API-only) or Thymeleaf',
    conventions: [
      'Layered architecture: Controller → Service → Repository',
      'Constructor injection (no field injection)',
      'DTO pattern for API request/response',
      'Bean Validation (jakarta.validation)',
      'JUnit 5 + Mockito for testing',
    ],
    patterns: {
      auth: 'Spring Security filter chain + JWT',
      data_fetching: 'Spring Data JPA repositories with query methods',
      validation: '@Valid + custom validators',
      errors: '@ControllerAdvice global exception handler',
    },
    file_structure: 'src/main/java/com/example/controller/, service/, repository/, model/, dto/, config/, src/test/',
    dependencies: ['spring-boot-starter-web', 'spring-boot-starter-data-jpa', 'spring-boot-starter-security', 'lombok'],
    anti_patterns: [
      'Never use field injection (@Autowired on fields)',
      'Never expose entities directly in API responses (use DTOs)',
      'Never catch generic Exception — be specific',
      'Never skip database migration tools (use Flyway/Liquibase)',
      'Never hardcode configuration — use application.yml profiles',
    ],
  },
  'dotnet-minimal': {
    name: 'dotnet-minimal',
    framework: '.NET 8 Minimal APIs',
    orm: 'Entity Framework Core',
    auth: 'ASP.NET Core Identity + JWT Bearer',
    ui_library: 'Blazor or none (API-only)',
    conventions: [
      'Minimal API with endpoint groups',
      'Vertical slice architecture (feature folders)',
      'MediatR for CQRS pattern',
      'FluentValidation for input validation',
      'xUnit + NSubstitute for testing',
    ],
    patterns: {
      auth: 'JWT Bearer + ASP.NET Identity',
      data_fetching: 'EF Core with IQueryable and projections',
      validation: 'FluentValidation + endpoint filters',
      errors: 'Problem Details (RFC 7807) for error responses',
    },
    file_structure: 'src/Api/Endpoints/, src/Domain/, src/Infrastructure/, src/Application/, tests/',
    dependencies: ['Microsoft.AspNetCore.App', 'Microsoft.EntityFrameworkCore', 'MediatR', 'FluentValidation'],
    anti_patterns: [
      'Never use async void (use async Task)',
      'Never skip cancellation token propagation',
      'Never return entities from endpoints (use DTOs/projections)',
      'Never ignore EF Core query tracking (use AsNoTracking for reads)',
      'Never put business logic in controllers/endpoints',
    ],
  },
};

// Merge all presets into one map
Object.assign(STACK_PRESETS, ADDITIONAL_STACK_PRESETS);
