import * as z from 'zod/v4';
import path from 'node:path';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { AppContext } from '../context.js';
import { writeFile } from '../utils/files.js';
import { PALETTES, FONT_PAIRINGS, UI_STYLES } from '../engines/design-engine/data.js';

function matchPalette(keywords: string[], industry?: string) {
  const lower = keywords.map((k) => k.toLowerCase());
  let best = PALETTES[0];
  let bestScore = 0;
  for (const p of PALETTES) {
    let score = 0;
    if (industry && p.industry.includes(industry)) score += 3;
    for (const kw of lower) {
      if (p.keywords.includes(kw)) score += 2;
      if (p.industry.some((i) => i.includes(kw))) score += 1;
      if (p.name.toLowerCase().includes(kw)) score += 1;
    }
    if (score > bestScore) { best = p; bestScore = score; }
  }
  return best;
}

function matchFont(keywords: string[]) {
  const lower = keywords.map((k) => k.toLowerCase());
  let best = FONT_PAIRINGS[0];
  let bestScore = 0;
  for (const f of FONT_PAIRINGS) {
    let score = 0;
    for (const kw of lower) {
      if (f.keywords.includes(kw)) score += 2;
      if (f.name.toLowerCase().includes(kw)) score += 1;
    }
    if (score > bestScore) { best = f; bestScore = score; }
  }
  return best;
}

function matchStyle(keywords: string[]) {
  const lower = keywords.map((k) => k.toLowerCase());
  let best = UI_STYLES[2]; // default: Minimal Flat
  let bestScore = 0;
  for (const s of UI_STYLES) {
    let score = 0;
    for (const kw of lower) {
      if (s.keywords.includes(kw)) score += 2;
      if (s.name.toLowerCase().includes(kw)) score += 1;
    }
    if (score > bestScore) { best = s; bestScore = score; }
  }
  return best;
}

export function registerDesignTool(server: McpServer, ctx: AppContext) {
  server.registerTool('loopspec_design', {
    title: 'Generate Design System',
    description: 'Generate a code-ready design system from keywords. Uses 31 palettes, 21 font pairings, 16 UI styles.',
    inputSchema: z.object({
      keywords: z.string().describe('Design keywords (e.g. "clean minimal fintech dark")'),
      industry: z.string().optional().describe('Industry (fintech, healthcare, ecommerce, education, saas, social)'),
      framework: z.string().optional().describe('CSS framework (tailwind, vanilla)'),
    }),
  }, async (args) => {
    const { keywords, industry } = args as { keywords: string; industry?: string; framework?: string };
    const kws = keywords.split(/[\s,]+/).filter(Boolean);
    const ind = industry || undefined;

    const palette = matchPalette(kws, ind);
    const fonts = matchFont(kws);
    const style = matchStyle(kws);

    const designSystem = `# Design System
> Generated by LoopSpec | Palette: ${palette.name} | Fonts: ${fonts.name} | Style: ${style.name}

## Color Tokens
\`\`\`css
:root {
  --color-primary: ${palette.primary};
  --color-secondary: ${palette.secondary};
  --color-accent: ${palette.accent};
  --color-bg: ${palette.bg};
  --color-text: ${palette.text};
  --color-muted: ${palette.muted};
  --color-border: ${palette.border};
  --color-success: #10B981;
  --color-warning: #F59E0B;
  --color-error: #EF4444;
}

[data-theme="dark"] {
  --color-bg: #0F172A;
  --color-text: #F1F5F9;
  --color-border: #334155;
  --color-muted: #94A3B8;
}
\`\`\`

## Typography
- Heading: **${fonts.heading}**
- Body: **${fonts.body}**${fonts.mono ? `\n- Mono: **${fonts.mono}**` : ''}
- CDN: \`https://fonts.googleapis.com/css2?family=${fonts.heading.replace(/ /g, '+')}:wght@400;500;600;700&family=${fonts.body.replace(/ /g, '+')}:wght@400;500;600&display=swap\`

## UI Style: ${style.name}
${style.description}

\`\`\`css
.card {
${Object.entries(style.cssProperties).map(([k, v]) => `  ${k}: ${v};`).join('\n')}
}
\`\`\`

## Tailwind Config
\`\`\`js
export default {
  theme: {
    extend: {
      colors: {
        primary: '${palette.primary}',
        secondary: '${palette.secondary}',
        accent: '${palette.accent}',
      },
      fontFamily: {
        heading: ['${fonts.heading}', 'sans-serif'],
        body: ['${fonts.body}', 'sans-serif'],
      },
      borderRadius: { sm: '0.25rem', md: '0.5rem', lg: '0.75rem', xl: '1rem', '2xl': '1.5rem' },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 4px 6px rgba(0,0,0,0.07)',
        lg: '0 10px 15px rgba(0,0,0,0.1)',
        xl: '0 20px 25px rgba(0,0,0,0.15)',
      },
    },
  },
}
\`\`\`

## Spacing Scale (base: 4px)
4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96

## Motion
- Micro: 150ms ease-out (hover, focus)
- Normal: 250ms ease-in-out (expand, collapse)
- Page: 400ms cubic-bezier(0.4, 0, 0.2, 1) (transitions)
- Always respect \`prefers-reduced-motion\`

## Anti-Patterns for "${style.name}"
${style.antiPatterns.map((a) => `- ❌ ${a}`).join('\n')}

## General UI Anti-Patterns
- ❌ No emoji as icons (use Lucide/Heroicons SVG)
- ❌ No layout-shifting hover effects (use opacity/color only)
- ❌ No text below 4.5:1 contrast ratio
- ❌ cursor-pointer on all interactive elements
- ❌ No horizontal scroll on mobile
`;

    await ctx.ensureLoopspecDir();
    await writeFile(path.join(ctx.loopspecDir, 'DesignSystem.md'), designSystem);
    return { content: [{ type: 'text' as const, text: designSystem }] };
  });
}
